# Generated by Django 3.2.25 on 2024-05-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('ship_number', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('register_date', models.DateTimeField(help_text='作成日')),
                ('order_date', models.DateTimeField(help_text='注文日')),
            ],
            options={
                'verbose_name_plural': 'ユーザ情報',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_address', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecsite.user')),
            ],
        ),
    ]
