# Generated by Django 3.2.25 on 2024-05-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
